export const q = queryStr => `mq__${queryStr}`;
export const MOCKATRON_CONSTRAINT_AND = `mc__AND`;
export const MOCKATRON_CONSTRAINT_TYPE_VALUE = `mc__CONSTRAINT-TYPE-VALUE`;
export const MOCKATRON_CONSTRAINT_TYPE_CONSTRAINT = `mc__CONSTRAINT-TYPE-CONSTRAINT`;
export const MOCKATRON_CONSTRAINT_CONDITION_NOT_EQ = `mc__CONSTRAINT-NOT-EQ`;
export const MOCKATRON_CONSTRAINT_UNDEFINED = `mc__CONSTRAINT-UNDEFINED`;